In [1]:
%pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


In [2]:
names = array(['bob', 'sue', 'jan', 'ad'])
weights = array([20.8, 93.2, 53.4, 61.8])

sort(weights)

array([20.8, 53.4, 61.8, 93.2])

In [3]:
ordered_indices = argsort(weights)
ordered_indices

array([0, 2, 3, 1], dtype=int64)

In [4]:
weights[ordered_indices]

array([20.8, 53.4, 61.8, 93.2])

In [5]:
names[ordered_indices]

array(['bob', 'jan', 'ad', 'sue'], dtype='<U3')

In [6]:
weights

array([20.8, 93.2, 53.4, 61.8])

In [7]:
data = array([20.8,  93.2,  53.4,  61.8])
data.argsort()

array([0, 2, 3, 1], dtype=int64)

In [8]:
data

array([20.8, 93.2, 53.4, 61.8])

In [9]:
data.sort()

In [10]:
data

array([20.8, 53.4, 61.8, 93.2])

In [11]:
a = array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])
a

array([[0.2, 0.1, 0.5],
       [0.4, 0.8, 0.3],
       [0.9, 0.6, 0.7]])

In [12]:
sort(a)

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.7, 0.9]])

In [13]:
sort(a, axis = 0)

array([[0.2, 0.1, 0.3],
       [0.4, 0.6, 0.5],
       [0.9, 0.8, 0.7]])

In [14]:
sorted_array = linspace(0,1,5)
values = array([.1,.8,.3,.12,.5,.25])

In [15]:
searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1], dtype=int64)

In [16]:
from numpy.random import rand
data = rand(100)
data.sort()

In [17]:
bounds = .4, .6
bounds

(0.4, 0.6)

In [18]:
low_idx, high_idx = searchsorted(data, bounds)

In [19]:
data[low_idx:high_idx]

array([0.40718963, 0.40970112, 0.41301107, 0.44169639, 0.45317531,
       0.46158307, 0.46676414, 0.47287782, 0.47406698, 0.48983535,
       0.50472977, 0.50522264, 0.50880651, 0.51001553, 0.52640701,
       0.56198648, 0.58014292, 0.5925599 , 0.59447832, 0.59760948])