In [1]:
from numpy import *

In [2]:
a = array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(2, 4)

In [5]:
a.size

8

In [6]:
a.itemsize

4

In [7]:
a.nbytes

32

In [8]:
a.ndim

2

In [10]:
for row in a:
    print (row)

[0 1 2 3]
[4 5 6 7]


In [11]:
for elt in a.flat:
    print (elt)

0
1
2
3
4
5
6
7


In [12]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
a.resize((4,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [15]:
a.swapaxes(0,1)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [16]:
a.transpose()

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [17]:
a.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [18]:
a2 = array([1,2,3])
a2.shape

(3,)

In [19]:
a2.resize((1,3,1))
a2.shape

(1, 3, 1)

In [20]:
a2 = a2.squeeze()
a2.shape

(3,)

In [21]:
b = a.copy()
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [22]:
b[0][0] = -1
b # First value changed

array([[-1,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7]])

In [23]:
a # original not changed because b is a copy

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [24]:
b.fill(4)
b

array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4]])

In [25]:
a.tolist()

[[0, 1], [2, 3], [4, 5], [6, 7]]

In [26]:
a.tostring()

b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00'

In [27]:
a.astype(float)

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.]])

In [28]:
b = a.copy()
b.byteswap(False)

array([[        0,  16777216],
       [ 33554432,  50331648],
       [ 67108864,  83886080],
       [100663296, 117440512]])

In [29]:
a.view(dtype=int16)

array([[0, 0, 1, 0],
       [2, 0, 3, 0],
       [4, 0, 5, 0],
       [6, 0, 7, 0]], dtype=int16)

In [30]:
b = array([1+2j, 3+4j, 5+6j])
b.real

array([1., 3., 5.])

In [31]:
b.imag

array([2., 4., 6.])

In [32]:
b.conj()

array([1.-2.j, 3.-4.j, 5.-6.j])

In [33]:
b.conjugate()

array([1.-2.j, 3.-4.j, 5.-6.j])

In [34]:
a.dump("file.txt")

In [35]:
a.dumps()

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x02\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i4q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X \x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [36]:
a.tofile('foo.csv', sep=',', format="%s")

In [37]:
a.nonzero()

(array([0, 1, 1, 2, 2, 3, 3], dtype=int64),
 array([1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [38]:
b = array([3,2,7,4,1])
b.sort()
b

array([1, 2, 3, 4, 7])

In [39]:
b = array([2,3,1])
b.argsort(axis=-1)

array([2, 0, 1], dtype=int64)

In [40]:
a = array([1,3,4,6])
b = array([0,2,5])
a.searchsorted(b)

array([0, 1, 3], dtype=int64)

In [41]:
a = array([[4,1,3],[2,1,5]])
a.clip(0,2)

array([[2, 1, 2],
       [2, 1, 2]])

In [42]:
a = array([1.344, 2.449, 2.558])
a.round(decimals=2)

array([1.34, 2.45, 2.56])

In [43]:
a = array([[4,1,3],[2,1,5]])
a.cumsum(axis=None)

array([ 4,  5,  8, 10, 11, 16], dtype=int32)

In [44]:
a.cumprod(axis=None)

array([  4,   4,  12,  24,  24, 120], dtype=int32)

In [45]:
a = array([[4,1,3],[2,1,5]])
a.sum(axis=None)

16

In [46]:
a.prod(axis=None)

120

In [47]:
a.max(axis=None)

5

In [48]:
a.argmin(axis=None)

1

In [49]:
a.argmax(axis=None)

5

In [50]:
a.ptp(axis=None)

4

In [51]:
a.mean(axis=None)

2.6666666666666665

In [52]:
a.std(axis=None)

1.49071198499986

In [53]:
a.var(axis=None)

2.2222222222222228

In [54]:
a.any(axis=None)

True

In [55]:
a.min(axis=None)

1

In [56]:
a.all()

True

In [57]:
import os
os.remove('foo.csv')
os.remove('file.txt')