In [1]:
import numpy as np

In [2]:
#hypot 返回对应点 (x,y) 到原点的距离
x = np.array([1,2,3])
y = np.array([4,5,6])
np.hypot(x,y)

array([4.12310563, 5.38516481, 6.70820393])

In [3]:
np.inf

inf

In [4]:
-np.inf

-inf

In [5]:
np.nan

nan

In [6]:
np.isinf(1.0)

False

In [7]:
np.isinf(np.inf)

True

In [8]:
np.isinf(-np.inf)

True

In [9]:
np.array([0]) / 0.0

d:\python36\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([nan])

In [10]:
a = np.arange(5.0)
b = a / 0.0
b

d:\python36\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: divide by zero encountered in true_divide
  from ipykernel import kernelapp as app
d:\python36\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


array([nan, inf, inf, inf, inf])

In [11]:
b == np.nan

array([False, False, False, False, False])

In [12]:
np.isnan(b)

array([ True, False, False, False, False])